[paige]
	[paige.site]
		color_scheme = "light" # options are ["light", "dark", "auto"]
		disable_breadcrumbs = true
		disable_credit = true
	[paige.pages]
		disable_authors = true
		disable_date = true
		disable_keywords = true
		disable_next = true
		disable_prev = true
		disable_reading_time = true
		disable_series = true
		disable_toc = true
		disable_word_count = true
	[paige.subpages]
		disable_authors = true
		disable_date = true
		disable_keywords = true
		disable_reading_time = true
		disable_series = true
		disable_summary = true
		disable_word_count = true